<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

/**
 * English strings for fileca
 *
 * @package    mod_fileca
 * @copyright  2025 Your Name
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['modulename'] = 'File CA';
$string['modulenameplural'] = 'File CAs';
$string['modulename_help'] = 'The File CA module allows teachers to provide a file as a course resource with advanced viewing and security features.';
$string['fileca:addinstance'] = 'Add a new File CA resource';
$string['fileca:view'] = 'View File CA content';
$string['pluginname'] = 'File CA';
$string['pluginadministration'] = 'File CA administration';

// Form strings.
$string['selectfiles'] = 'Select file';
$string['selectfiles_help'] = 'Upload a file to share with students. Supported formats include PDF, Word documents, PowerPoint presentations, and Excel spreadsheets.';
$string['behaviour'] = 'Behaviour';
$string['enabledownload'] = 'Enable file download';
$string['enabledownload_help'] = 'If enabled, students can download the file. If disabled, they can only view it online.';
$string['enableprinting'] = 'Enable printing';
$string['enableprinting_help'] = 'If enabled, students can print the PDF. If disabled, printing is prevented.';
$string['enablecopying'] = 'Enable copying';
$string['enablecopying_help'] = 'If enabled, students can select and copy text from the PDF. If disabled, text selection is prevented.';
$string['enablesummarize'] = 'Enable summarize';
$string['enablesummarize_help'] = 'If enabled, students can generate a summary of the file content using AI.';

// View strings.
$string['nofile'] = 'No file has been uploaded yet.';
$string['download'] = 'Download';
$string['summarize'] = 'Summarize';
$string['downloadnotenabled'] = 'Downloads are not enabled for this file.';
$string['nofilecas'] = 'No File CA activities found in this course.';
$string['intro'] = 'Description';
$string['page-mod-fileca-x'] = 'Any File CA module page';

// Summarize strings.
$string['summarizing'] = 'Generating summary';
$string['summary'] = 'Summary';
$string['summarizeerror'] = 'Error generating summary. Please try again.';
$string['summarysuccess'] = 'Summary generated successfully';
$string['summarizenotenabled'] = 'Summarization is not enabled for this file.';
$string['summaryplaceholder'] = 'This is a summary of the document. In a production environment, this would be generated by an AI service analyzing the document content.';
$string['summarizenotsupported'] = 'Summarization is not yet supported for this file type.';
